### ISSUE TITLE
Negative percentage allowed for goal

### ISSUE THREAD

**Issue by 5tigerjelly** [jmatray/ThreeMusketeers#1]
![image](https://user-images.githubusercontent.com/15973528/40895071-330520d0-6762-11e8-8461-4718f45102af.png)

in goals tab, I was able to insert `-10`  for savings, `-100` for spending: Necessities and `10` for Spending: Discretionary

**Comment by jmatray** [comment]
Fixed this issues, so that the validation state of the input box no longer recognizes negative values as acceptable.
