### ISSUE TITLE
Not clear input boxes. 

### ISSUE THREAD

**Issue by Kidusyohanes** [jmatray/ThreeMusketeers#10]
Recreation steps: 

1. Log-in 
2. Click 'Expenses'

Under expenses: there is no clear input box until a user hovers on top or clicks next to it. 
<img width="293" alt="screen shot 2018-06-04 at 4 50 27 pm" src="https://user-images.githubusercontent.com/17691298/40947421-6c19cc30-6817-11e8-96f9-902eb0f70f56.png">

**Comment by mariechristinesmet** [comment]
Thank you for pointing this out! After following the recreation steps of logging in and clicking expenses, we were unable to reproduce this bug (see image below of Expenses page displaying clear input boxes) and therefore are not considering it a real failure. Additionally, these input boxes do not affect major functionality of this page, whether or not users can successfully add the amount they spend on expenses per month.

![image](https://user-images.githubusercontent.com/32251054/40999455-cb44515a-68bf-11e8-9ee7-d68c36682af9.png)

**Comment by abegel** [comment]
@Kidusyohanes can you say more about the conditions you used to reproduce this bug? Browser type? OS? Version?

**Comment by Kidusyohanes** [comment]
It's not a bug but It was not clear as a user if that was an input box or a display of values. The updated UI made it clear that it is, in fact, an input box and not a display. I used Chrome (V8 engine), on iOS. @abegel
