### ISSUE TITLE
NaN Errors On Dashboard

### ISSUE THREAD

**Issue by alexiskoss** [jmatray/ThreeMusketeers#3]
Not really sure how I got this error, but you can see the following numbers that I put in gave me NaN for all suggested spending and progress bars.

<img width="1325" alt="screen shot 2018-06-03 at 9 00 35 pm" src="https://user-images.githubusercontent.com/22551612/40897842-3a697320-6772-11e8-93b2-0ee11e6cbed7.png">

[MAJOR]

**Reproduction steps:**
1. Filled out the basic info survey with the following information:
- Estimated monthly income: 5,000 
- Estimated monthly savings: 2,000 
- Are you a student? Yes. 
- Are you a dependent? No. 
- Number of depends you have: 0 
- Number of members in your household: 2
- Do you work less than 40 hours a week? Yes.

2. Filled out expenses with the following information:
- Housing: 550 
- Utilities: 50 
- Food: 250 
- Transportation: 25 
- Misc: 404

3. Filled out goals with the following information:
- Savings: 50%
- Necessities: 25%
- Discretionaries: 25%

4. Clicked on Dashboard (and refreshed it too) and have NaN appearing for suggested spending and progress thus far.

**Comment by hmansoori** [comment]
Changed type of input forms to "number" instead of "text", prevents non-number values from being entered (3,000 is not valid but 3000 is).
