### ISSUE TITLE
Goal setting allows me to set percentage above 100%

### ISSUE THREAD

**Issue by johnwjlim** [jmatray/ThreeMusketeers#6]
Reproduction steps:
1) Go to goals
2) Set percentage for each field to about a gazillion
3) Press save and wonder why I pretty much never achieve any of my goals 

![image](https://user-images.githubusercontent.com/34074206/40902694-bee155f2-6789-11e8-8438-7a351dc5902c.png)

**Comment by jmatray** [comment]
Fixed this issue where one error (setting savings too high) cancels out the error that prevents updating goals (goal percentages not equal to 100)
