### ISSUE TITLE
Overflowing input completely breaks the website

### ISSUE THREAD

**Issue by harrybarng** [jmatray/ThreeMusketeers#7]
I inputted 3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333

in the expense boxes and this happened: https://drive.google.com/open?id=1R6mqKJREGNH0DIsaJ_QCTCM1u54KQ6qT

**Comment by hmansoori** [comment]
To remedy this issue, we decided that 1,000,000 should be the limit for monthly income, savings, and expenses. This will prevent too large of values from being entered, which is what caused this bug. Forms will not accept values of over 1,000,000 as valid input.
