### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by AntonZheng** [jmatray/ThreeMusketeers#9]
The formatting of numbers overflows the div when inputting big numbers.

![screen shot 2018-06-04 at 1 33 08 am](https://user-images.githubusercontent.com/16981362/40907060-795b8ff8-6797-11e8-8a6c-a8c28e847d22.png)

**Comment by hmansoori** [comment]
By making the maximum amount of monetary values 1,000,000 as well as by limiting all values to two decimal places, we can prevent this formatting bug. Values now fit within the graphs and tables even at their maximum value.
